# ROBOTICS-ML-AI CHANNEL PROJECT ON DATA WRANGLING

### Pandas Project: Make a gradebook with Pandas

This project entails calculating student grades by combining data from many sources. We will be using data from the
* Roster
* Homework & Exam grades
* Quiz grades

In [1]:
import os
import glob
import numpy as np
import pandas as pd

##### Loading the data

In [2]:
data_folder = 'data'

In [3]:
roster = pd.read_csv(
    os.path.join(data_folder,"roster.csv"),
    converters={"NetID": str.lower, "Email Address": str.lower},
    usecols=["Section", "Email Address", "NetID"],
    index_col="NetID",
)
roster

Email Address  Section
NetID                                       
wxb12345  woody.barrera_jr@univ.edu        1
mxl12345   malaika.lambert@univ.edu        2
txj12345       traci.joyce@univ.edu        1
jgf12345   john.g.2.flower@univ.edu        3
smj00936     stacy.johnson@univ.edu        2
...                             ...      ...
pmj37756      paul.johnson@univ.edu        3
dsl24347      danielle.lee@univ.edu        3
nxe44872    nicole.edwards@univ.edu        3
bxr62103      bailey.reyes@univ.edu        2
jxw53347       joyce.walls@univ.edu        1

[150 rows x 2 columns]

In [4]:
 hw_exam_grades = pd.read_csv(
    os.path.join(data_folder,"hw_exam_grades.csv"),
    converters={"SID": str.lower},
    usecols=lambda x: "Submission" not in x,
    index_col="SID",
    
)
hw_exam_grades 

First Name   Last Name  Homework 1  Homework 1 - Max Points  \
SID                                                                    
axl60952      Aaron      Lester        68.0                       80   
amc28428       Adam      Cooper        80.0                       80   
axc64717       Alec       Curry        69.0                       80   
akr14831  Alexander   Rodriguez        50.0                       80   
axd11293      Amber     Daniels        54.0                       80   
...             ...         ...         ...                      ...   
txw75701     Travis  Washington        64.0                       80   
tbr17292       Troy     Raymond        50.0                       80   
vkb66346   Victoria        Boyd        58.0                       80   
wad63934    William      Daniel        48.0                       80   
wxb12345      Woody     Barrera        55.0                       80   

          Homework 2  Homework 2 - Max Points  Homework 3  \
SID                                                         
axl60952          74                       80          77   
amc28428          78                       80          78   
axc64717          76                       80          66   
akr14831          54                       80          74   
axd11293          57                       80          77   
...              ...                      ...         ...   
txw75701          67                       80          56   
tbr17292          59                       80          79   
vkb66346          61                       80          75   
wad63934          60                       80          72   
wxb12345          62                       80          73   

          Homework 3 - Max Points  Homework 4  Homework 4 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          89                      100  ...   
amc28428                       80          87                      100  ...   
axc64717                       80          87                      100  ...   
akr14831                       80          75                      100  ...   
axd11293                       80          95                      100  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          92                      100  ...   
tbr17292                       80          98                      100  ...   
vkb66346                       80          99                      100  ...   
wad63934                       80          76                      100  ...   
wxb12345                       80          83                      100  ...   

          Homework 9  Homework 9 - Max Points  Homework 10  \
SID                                                          
axl60952          42                       60           41   
amc28428          45                       60           53   
axc64717          58                       60           42   
akr14831          38                       60           47   
axd11293          46                       60           59   
...              ...                      ...          ...   
txw75701          40                       60           52   
tbr17292          45                       60           49   
vkb66346          40                       60           50   
wad63934          51                       60           36   
wxb12345          45                       60           46   

          Homework 10 - Max Points  Exam 1  Exam 1 - Max Points  Exam 2  \
SID                                                                       
axl60952                        60      79                  100      63   
amc28428                        60      65                  100      63   
axc64717                        60      65                  100      78   
akr14831                        60      97                  100     

In [5]:
quiz_grades = pd.DataFrame()
for file_path in glob.glob("data/quiz_*_grades.csv"):
    quiz_name = " ".join(file_path[5:].split("_")[:2])
    quiz = pd.read_csv(
        file_path,
        converters={"Email": str.lower},
        index_col=["Email"],
        usecols=["Email", "Grade"],
    ).rename(columns={"Grade": quiz_name})
    quiz_grades = pd.concat([quiz_grades, quiz], axis=1)

In [6]:
quiz_grades

quiz 1  quiz 2  quiz 3  quiz 4  quiz 5
Email                                                           
richard.bennett@univ.edu      10       6       9       8      10
timothy.parker@univ.edu        9      14      13      14      10
carol.reyes@univ.edu           5      15       8      14       6
brooke.powers@univ.edu         6      10      17      10       8
michael.taylor@univ.edu        5      15      13      12       5
...                          ...     ...     ...     ...     ...
jeffrey.perez@univ.edu         4       7      12      12       9
angela.dunlap@univ.edu         6      11      11      11       6
richard.elliott@univ.edu       6      13      17      11      12
donna.nguyen@univ.edu          7      12      14       9       4
timothy.ramirez@univ.edu       4       8      13       6       4

[150 rows x 5 columns]

##### Merging data

In [7]:
# Merge all the imported tables together. Hint: merge data with similar columns first before joining all
df1 = pd.merge(roster, hw_exam_grades, right_on='SID', left_index=True)
merged_data = pd.merge(df1, quiz_grades, left_on='Email Address', right_index=True, how='outer')
merged_data

Email Address  Section First Name   Last Name  \
SID                                                                      
axl60952         aaron.lester@univ.edu        2      Aaron      Lester   
amc28428          adam.cooper@univ.edu        2       Adam      Cooper   
axc64717           alec.curry@univ.edu        2       Alec       Curry   
akr14831  alexander.rodriguez@univ.edu        2  Alexander   Rodriguez   
axd11293        amber.daniels@univ.edu        2      Amber     Daniels   
...                                ...      ...        ...         ...   
txw75701    travis.washington@univ.edu        1     Travis  Washington   
tbr17292         troy.raymond@univ.edu        3       Troy     Raymond   
vkb66346        victoria.boyd@univ.edu        2   Victoria        Boyd   
wad63934       william.daniel@univ.edu        2    William      Daniel   
wxb12345     woody.barrera_jr@univ.edu        1      Woody     Barrera   

          Homework 1  Homework 1 - Max Points  Homework 2  \
SID                                                         
axl60952        68.0                       80          74   
amc28428        80.0                       80          78   
axc64717        69.0                       80          76   
akr14831        50.0                       80          54   
axd11293        54.0                       80          57   
...              ...                      ...         ...   
txw75701        64.0                       80          67   
tbr17292        50.0                       80          59   
vkb66346        58.0                       80          61   
wad63934        48.0                       80          60   
wxb12345        55.0                       80          62   

          Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          77                       80  ...   
amc28428                       80          78                       80  ...   
axc64717                       80          66                       80  ...   
akr14831                       80          74                       80  ...   
axd11293                       80          77                       80  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          56                       80  ...   
tbr17292                       80          79                       80  ...   
vkb66346                       80          75                       80  ...   
wad63934                       80          72                       80  ...   
wxb12345                       80          73                       80  ...   

          Exam 1 - Max Points  Exam 2  Exam 2 - Max Points  Exam 3  \
SID                                                                  
axl60952                  100      63                  100      68   
amc28428                  100      63                  100      90   
axc64717                  100      78                  100      83   
akr14831                  100      97                  100      81   
axd11293                  100      95                  100      88   
...                       ...     ...                  ...     ...   
txw75701                  100      74                  100      68   
tbr17292                  100      67                  100     100   
vkb66346                  100      93                  100      69   
wad63934                  100      91                  100      95   
wxb12345                  100      62                  100      90   

          Exam 3 - Max Points  quiz 1  quiz 2  quiz 3  quiz 4  quiz 5  
SID                                                                    
axl60952                  100       6       9      10       8       8  
amc28428                  100       4      10      16       7      12  
axc64717                  100       9    

##### Exploring data

In [8]:
# show the shape of the data
merged_data.shape

(150, 35)

In [9]:
#show the number of unique emails
print(merged_data['Email Address'].nunique())

150


In [10]:
# show a summary information of the final data 
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, axl60952 to wxb12345
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Email Address             150 non-null    object 
 1   Section                   150 non-null    int64  
 2   First Name                150 non-null    object 
 3   Last Name                 150 non-null    object 
 4   Homework 1                149 non-null    float64
 5   Homework 1 - Max Points   150 non-null    int64  
 6   Homework 2                150 non-null    int64  
 7   Homework 2 - Max Points   150 non-null    int64  
 8   Homework 3                150 non-null    int64  
 9   Homework 3 - Max Points   150 non-null    int64  
 10  Homework 4                150 non-null    int64  
 11  Homework 4 - Max Points   150 non-null    int64  
 12  Homework 5                150 non-null    int64  
 13  Homework 5 - Max Points   150 non-null    int64  
 14  Hom

In [11]:
# check for null/missing values
merged_data.isnull().sum()

Email Address               0
Section                     0
First Name                  0
Last Name                   0
Homework 1                  1
Homework 1 - Max Points     0
Homework 2                  0
Homework 2 - Max Points     0
Homework 3                  0
Homework 3 - Max Points     0
Homework 4                  0
Homework 4 - Max Points     0
Homework 5                  0
Homework 5 - Max Points     0
Homework 6                  0
Homework 6 - Max Points     0
Homework 7                  0
Homework 7 - Max Points     0
Homework 8                  0
Homework 8 - Max Points     0
Homework 9                  0
Homework 9 - Max Points     0
Homework 10                 0
Homework 10 - Max Points    0
Exam 1                      0
Exam 1 - Max Points         0
Exam 2                      0
Exam 2 - Max Points         0
Exam 3                      0
Exam 3 - Max Points         0
quiz 1                      0
quiz 2                      0
quiz 3                      0
quiz 4    

In [12]:
# replace all missing values with 0
new_merged_data = merged_data.fillna(0)

In [13]:
# show a mathematical summary of the data
new_merged_data.describe()

Section  Homework 1  Homework 1 - Max Points  Homework 2  \
count  150.000000   150.00000                    150.0  150.000000   
mean     1.913333    62.02000                     80.0   64.526667   
std      0.810474    10.98044                      0.0   10.000468   
min      1.000000     0.00000                     80.0   48.000000   
25%      1.000000    53.00000                     80.0   55.250000   
50%      2.000000    62.00000                     80.0   65.000000   
75%      3.000000    70.75000                     80.0   74.000000   
max      3.000000    80.00000                     80.0   80.000000   

       Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  \
count                    150.0  150.000000                    150.0   
mean                      80.0   63.173333                     80.0   
std                        0.0    9.326117                      0.0   
min                       80.0   48.000000                     80.0   
25%                       80.0   55.000000                     80.0   
50%                       80.0   62.000000                     80.0   
75%                       80.0   72.000000                     80.0   
max                       80.0   80.000000                     80.0   

       Homework 4  Homework 4 - Max Points  Homework 5  ...  \
count  150.000000                    150.0  150.000000  ...   
mean    78.686667                    100.0   55.353333  ...   
std     10.971064                      0.0    8.457661  ...   
min     60.000000                    100.0   42.000000  ...   
25%     69.000000                    100.0   47.250000  ...   
50%     78.000000                    100.0   55.000000  ...   
75%     87.000000                    100.0   63.000000  ...   
max    100.000000                    100.0   70.000000  ...   

       Exam 1 - Max Points      Exam 2  Exam 2 - Max Points      Exam 3  \
count                150.0  150.000000                150.0  150.000000   
mean                 100.0   80.593333                100.0   81.486667   
std                    0.0   12.289078                  0.0   12.482867   
min                  100.0   60.000000                100.0   60.000000   
25%                  100.0   70.000000                100.0   68.250000   
50%                  100.0   80.000000                100.0   84.000000   
75%                  100.0   92.000000                100.0   92.750000   
max                  100.0  100.000000                100.0  100.000000   

       Exam 3 - Max Points      quiz 1      quiz 2      quiz 3      quiz 4  \
count                150.0  150.000000  150.000000  150.000000  150.000000   
mean                 100.0    7.413333   10.886667   11.640000    9.506667   
std                    0.0    2.127439    2.945903    3.458828    2.928102   
min                  100.0    4.000000    6.000000    6.000000    5.000000   
25%                  100.0    6.000000    8.000000    9.000000    7.000000   
50%                  100.0    7.000000   11.000000   12.000000    9.500000   
75%                  100.0    9.000000   14.000000   14.000000   12.000000   
max                  100.0   11.000000   15.000000   17.000000   14.000000   

           quiz 5  
count  150.000000  
mean     7.853333  
std      2.668199  
min      4.000000  
25%      5.250000  
50%      8.000000  
75%     10.000000  
max     12.000000  

[8 rows x 32 columns]

In [14]:
# check if data contains any duplicates in the email column
new_merged_data.duplicated(subset=['Email Address'], keep=False).sum()

0

##### Feature Engineering by calculating the grades

In [15]:
# create a new column that holds the calculated exam score of each student. Hint: divide exam 1 / exam 1 - maxpoints to get the
# calculated score of each student for exam 1
Exam_1_score = new_merged_data['Exam 1']/new_merged_data['Exam 1 - Max Points']
Exam_2_score = new_merged_data['Exam 2']/new_merged_data['Exam 2 - Max Points']
Exam_3_score = new_merged_data['Exam 3']/new_merged_data['Exam 3 - Max Points']
new_merged_data['Exam 1 Score'] = Exam_1_score
new_merged_data['Exam 2 Score'] = Exam_2_score
new_merged_data['Exam 3 Score'] = Exam_3_score
new_merged_data


Email Address  Section First Name   Last Name  \
SID                                                                      
axl60952         aaron.lester@univ.edu        2      Aaron      Lester   
amc28428          adam.cooper@univ.edu        2       Adam      Cooper   
axc64717           alec.curry@univ.edu        2       Alec       Curry   
akr14831  alexander.rodriguez@univ.edu        2  Alexander   Rodriguez   
axd11293        amber.daniels@univ.edu        2      Amber     Daniels   
...                                ...      ...        ...         ...   
txw75701    travis.washington@univ.edu        1     Travis  Washington   
tbr17292         troy.raymond@univ.edu        3       Troy     Raymond   
vkb66346        victoria.boyd@univ.edu        2   Victoria        Boyd   
wad63934       william.daniel@univ.edu        2    William      Daniel   
wxb12345     woody.barrera_jr@univ.edu        1      Woody     Barrera   

          Homework 1  Homework 1 - Max Points  Homework 2  \
SID                                                         
axl60952        68.0                       80          74   
amc28428        80.0                       80          78   
axc64717        69.0                       80          76   
akr14831        50.0                       80          54   
axd11293        54.0                       80          57   
...              ...                      ...         ...   
txw75701        64.0                       80          67   
tbr17292        50.0                       80          59   
vkb66346        58.0                       80          61   
wad63934        48.0                       80          60   
wxb12345        55.0                       80          62   

          Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          77                       80  ...   
amc28428                       80          78                       80  ...   
axc64717                       80          66                       80  ...   
akr14831                       80          74                       80  ...   
axd11293                       80          77                       80  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          56                       80  ...   
tbr17292                       80          79                       80  ...   
vkb66346                       80          75                       80  ...   
wad63934                       80          72                       80  ...   
wxb12345                       80          73                       80  ...   

          Exam 3  Exam 3 - Max Points  quiz 1  quiz 2  quiz 3  quiz 4  quiz 5  \
SID                                                                             
axl60952      68                  100       6       9      10       8       8   
amc28428      90                  100       4      10      16       7      12   
axc64717      83                  100       9       9       9      12      11   
akr14831      81                  100      11      13      16      11       7   
axd11293      88                  100       7      15      16       5       6   
...          ...                  ...     ...     ...     ...     ...     ...   
txw75701      68                  100      11      13      10       9       8   
tbr17292     100                  100       7       7      14       7       5   
vkb66346      69                  100       9       8       6       6       8   
wad63934      95                  100       9      10      10       9       5   
wxb12345      90                  100       4      10      11       7      10   

          Exam 1 Score  Exam 2 Score  Exam 3 Score  
SID                                                 
axl60952          0.79          0.63          0.68  
amc28428          0.65     

In [16]:
# for the homework, we are summing from 1 to n together per student, not separately like for exams.
# Hint use the filter method and regex to get all the homework columns in one place.
# Hint for regex "^Homework \d\d?$"
#Then sum all the values per row, for homework and homework max, then get the total homework score per student by dividing the
# homework score by the max homework score
hw_sum = new_merged_data[['Homework 1', 'Homework 2', 'Homework 3']].sum(axis=1)
hw_max_points_sum = new_merged_data[['Homework 1 - Max Points', 'Homework 2 - Max Points', 'Homework 3 - Max Points']].sum(axis=1)
new_merged_data['Homework Score'] = hw_sum / hw_max_points_sum
new_merged_data

Email Address  Section First Name   Last Name  \
SID                                                                      
axl60952         aaron.lester@univ.edu        2      Aaron      Lester   
amc28428          adam.cooper@univ.edu        2       Adam      Cooper   
axc64717           alec.curry@univ.edu        2       Alec       Curry   
akr14831  alexander.rodriguez@univ.edu        2  Alexander   Rodriguez   
axd11293        amber.daniels@univ.edu        2      Amber     Daniels   
...                                ...      ...        ...         ...   
txw75701    travis.washington@univ.edu        1     Travis  Washington   
tbr17292         troy.raymond@univ.edu        3       Troy     Raymond   
vkb66346        victoria.boyd@univ.edu        2   Victoria        Boyd   
wad63934       william.daniel@univ.edu        2    William      Daniel   
wxb12345     woody.barrera_jr@univ.edu        1      Woody     Barrera   

          Homework 1  Homework 1 - Max Points  Homework 2  \
SID                                                         
axl60952        68.0                       80          74   
amc28428        80.0                       80          78   
axc64717        69.0                       80          76   
akr14831        50.0                       80          54   
axd11293        54.0                       80          57   
...              ...                      ...         ...   
txw75701        64.0                       80          67   
tbr17292        50.0                       80          59   
vkb66346        58.0                       80          61   
wad63934        48.0                       80          60   
wxb12345        55.0                       80          62   

          Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          77                       80  ...   
amc28428                       80          78                       80  ...   
axc64717                       80          66                       80  ...   
akr14831                       80          74                       80  ...   
axd11293                       80          77                       80  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          56                       80  ...   
tbr17292                       80          79                       80  ...   
vkb66346                       80          75                       80  ...   
wad63934                       80          72                       80  ...   
wxb12345                       80          73                       80  ...   

          Exam 3 - Max Points  quiz 1  quiz 2  quiz 3  quiz 4  quiz 5  \
SID                                                                     
axl60952                  100       6       9      10       8       8   
amc28428                  100       4      10      16       7      12   
axc64717                  100       9       9       9      12      11   
akr14831                  100      11      13      16      11       7   
axd11293                  100       7      15      16       5       6   
...                       ...     ...     ...     ...     ...     ...   
txw75701                  100      11      13      10       9       8   
tbr17292                  100       7       7      14       7       5   
vkb66346                  100       9       8       6       6       8   
wad63934                  100       9      10      10       9       5   
wxb12345                  100       4      10      11       7      10   

          Exam 1 Score  Exam 2 Score  Exam 3 Score  Homework Score  
SID                                                                 
axl60952          0.79          0.63          0.68        0.912500  
amc28428          0.65          0.63          0.90        0.983333  
axc64717      

In [17]:
# for the quiz, we are using the style used in homework.

# Use this for the quiz max points
quiz_max_points = pd.Series(
    {"Quiz 1": 11, "Quiz 2": 15, "Quiz 3": 17, "Quiz 4": 14, "Quiz 5": 12}
)
# Hint use the filter method and regex to get all the quiz columns in one place and the homework max columns.
# Hint for regex "^Quiz \d$"
#Then sum all the values per row, for quiz, then get the total quiz score per student by dividing the
# homework score by the max homework score
qz_sum = new_merged_data[['quiz 1', 'quiz 2', 'quiz 3', 'quiz 4', 'quiz 5']].sum(axis=1)
qz_max_points_sum = quiz_max_points.sum()
new_merged_data['Quiz Score'] = qz_sum / qz_max_points_sum
new_merged_data

Email Address  Section First Name   Last Name  \
SID                                                                      
axl60952         aaron.lester@univ.edu        2      Aaron      Lester   
amc28428          adam.cooper@univ.edu        2       Adam      Cooper   
axc64717           alec.curry@univ.edu        2       Alec       Curry   
akr14831  alexander.rodriguez@univ.edu        2  Alexander   Rodriguez   
axd11293        amber.daniels@univ.edu        2      Amber     Daniels   
...                                ...      ...        ...         ...   
txw75701    travis.washington@univ.edu        1     Travis  Washington   
tbr17292         troy.raymond@univ.edu        3       Troy     Raymond   
vkb66346        victoria.boyd@univ.edu        2   Victoria        Boyd   
wad63934       william.daniel@univ.edu        2    William      Daniel   
wxb12345     woody.barrera_jr@univ.edu        1      Woody     Barrera   

          Homework 1  Homework 1 - Max Points  Homework 2  \
SID                                                         
axl60952        68.0                       80          74   
amc28428        80.0                       80          78   
axc64717        69.0                       80          76   
akr14831        50.0                       80          54   
axd11293        54.0                       80          57   
...              ...                      ...         ...   
txw75701        64.0                       80          67   
tbr17292        50.0                       80          59   
vkb66346        58.0                       80          61   
wad63934        48.0                       80          60   
wxb12345        55.0                       80          62   

          Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          77                       80  ...   
amc28428                       80          78                       80  ...   
axc64717                       80          66                       80  ...   
akr14831                       80          74                       80  ...   
axd11293                       80          77                       80  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          56                       80  ...   
tbr17292                       80          79                       80  ...   
vkb66346                       80          75                       80  ...   
wad63934                       80          72                       80  ...   
wxb12345                       80          73                       80  ...   

          quiz 1  quiz 2  quiz 3  quiz 4  quiz 5  Exam 1 Score  Exam 2 Score  \
SID                                                                            
axl60952       6       9      10       8       8          0.79          0.63   
amc28428       4      10      16       7      12          0.65          0.63   
axc64717       9       9       9      12      11          0.65          0.78   
akr14831      11      13      16      11       7          0.97          0.97   
axd11293       7      15      16       5       6          0.68          0.95   
...          ...     ...     ...     ...     ...           ...           ...   
txw75701      11      13      10       9       8          0.94          0.74   
tbr17292       7       7      14       7       5          0.91          0.67   
vkb66346       9       8       6       6       8          0.68          0.93   
wad63934       9      10      10       9       5          0.84          0.91   
wxb12345       4      10      11       7      10          0.86          0.62   

          Exam 3 Score  Homework Score  Quiz Score  
SID                                                 
axl60952          0.68        0.912500    0.594203  
amc28428          0.90        0.983333  

In [18]:
# apply weight to each score: exam1,2,3,homework and quiz score, i.e multiply the values in these final columns by their weights
#use this weights
weightings = pd.Series(
    {
        "Exam 1 Score": 0.2,
        "Exam 2 Score": 0.15,
        "Exam 3 Score": 0.25,
        "Quiz Score": 0.20,
        "Homework Score": 0.20,
    }
)
# the final score should be the sum per row after mutiplying each score by its respective weights
new_merged_data['Final Score'] = (new_merged_data['Exam 1 Score']*weightings['Exam 1 Score']) + (new_merged_data['Exam 2 Score']*weightings['Exam 2 Score']) + (new_merged_data['Exam 3 Score']*weightings['Exam 3 Score']) + (new_merged_data['Quiz Score']*weightings['Quiz Score']) + (new_merged_data['Homework Score']*weightings['Homework Score'])
# then get the ceiling score by ceiling the final score * 100
new_merged_data['Ceiling Score'] = new_merged_data['Final Score']*100
new_merged_data['Ceiling Score'] = new_merged_data['Ceiling Score'].apply(np.ceil)
new_merged_data

Email Address  Section First Name   Last Name  \
SID                                                                      
axl60952         aaron.lester@univ.edu        2      Aaron      Lester   
amc28428          adam.cooper@univ.edu        2       Adam      Cooper   
axc64717           alec.curry@univ.edu        2       Alec       Curry   
akr14831  alexander.rodriguez@univ.edu        2  Alexander   Rodriguez   
axd11293        amber.daniels@univ.edu        2      Amber     Daniels   
...                                ...      ...        ...         ...   
txw75701    travis.washington@univ.edu        1     Travis  Washington   
tbr17292         troy.raymond@univ.edu        3       Troy     Raymond   
vkb66346        victoria.boyd@univ.edu        2   Victoria        Boyd   
wad63934       william.daniel@univ.edu        2    William      Daniel   
wxb12345     woody.barrera_jr@univ.edu        1      Woody     Barrera   

          Homework 1  Homework 1 - Max Points  Homework 2  \
SID                                                         
axl60952        68.0                       80          74   
amc28428        80.0                       80          78   
axc64717        69.0                       80          76   
akr14831        50.0                       80          54   
axd11293        54.0                       80          57   
...              ...                      ...         ...   
txw75701        64.0                       80          67   
tbr17292        50.0                       80          59   
vkb66346        58.0                       80          61   
wad63934        48.0                       80          60   
wxb12345        55.0                       80          62   

          Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          77                       80  ...   
amc28428                       80          78                       80  ...   
axc64717                       80          66                       80  ...   
akr14831                       80          74                       80  ...   
axd11293                       80          77                       80  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          56                       80  ...   
tbr17292                       80          79                       80  ...   
vkb66346                       80          75                       80  ...   
wad63934                       80          72                       80  ...   
wxb12345                       80          73                       80  ...   

          quiz 3  quiz 4  quiz 5  Exam 1 Score  Exam 2 Score  Exam 3 Score  \
SID                                                                          
axl60952      10       8       8          0.79          0.63          0.68   
amc28428      16       7      12          0.65          0.63          0.90   
axc64717       9      12      11          0.65          0.78          0.83   
akr14831      16      11       7          0.97          0.97          0.81   
axd11293      16       5       6          0.68          0.95          0.88   
...          ...     ...     ...           ...           ...           ...   
txw75701      10       9       8          0.94          0.74          0.68   
tbr17292      14       7       5          0.91          0.67          1.00   
vkb66346       6       6       8          0.68          0.93          0.69   
wad63934      10       9       5          0.84          0.91          0.95   
wxb12345      11       7      10          0.86          0.62          0.90   

          Homework Score  Quiz Score  Final Score  Ceiling Score  
SID                                                               
axl60952        0.912500    0.594203     0.723841           73.0  
amc28428        0.983333

In [19]:
# Finally map each students grade to this in a new column
grades = {
    90: "A",
    80: "B",
    70: "C",
    60: "D",
    0: "F",
}
def map_grades(n):
    for grade in grades:
        if n >= grade:
            return grades[grade]
new_merged_data['Grade'] = new_merged_data['Ceiling Score'].map(map_grades)
new_merged_data

Email Address  Section First Name   Last Name  \
SID                                                                      
axl60952         aaron.lester@univ.edu        2      Aaron      Lester   
amc28428          adam.cooper@univ.edu        2       Adam      Cooper   
axc64717           alec.curry@univ.edu        2       Alec       Curry   
akr14831  alexander.rodriguez@univ.edu        2  Alexander   Rodriguez   
axd11293        amber.daniels@univ.edu        2      Amber     Daniels   
...                                ...      ...        ...         ...   
txw75701    travis.washington@univ.edu        1     Travis  Washington   
tbr17292         troy.raymond@univ.edu        3       Troy     Raymond   
vkb66346        victoria.boyd@univ.edu        2   Victoria        Boyd   
wad63934       william.daniel@univ.edu        2    William      Daniel   
wxb12345     woody.barrera_jr@univ.edu        1      Woody     Barrera   

          Homework 1  Homework 1 - Max Points  Homework 2  \
SID                                                         
axl60952        68.0                       80          74   
amc28428        80.0                       80          78   
axc64717        69.0                       80          76   
akr14831        50.0                       80          54   
axd11293        54.0                       80          57   
...              ...                      ...         ...   
txw75701        64.0                       80          67   
tbr17292        50.0                       80          59   
vkb66346        58.0                       80          61   
wad63934        48.0                       80          60   
wxb12345        55.0                       80          62   

          Homework 2 - Max Points  Homework 3  Homework 3 - Max Points  ...  \
SID                                                                     ...   
axl60952                       80          77                       80  ...   
amc28428                       80          78                       80  ...   
axc64717                       80          66                       80  ...   
akr14831                       80          74                       80  ...   
axd11293                       80          77                       80  ...   
...                           ...         ...                      ...  ...   
txw75701                       80          56                       80  ...   
tbr17292                       80          79                       80  ...   
vkb66346                       80          75                       80  ...   
wad63934                       80          72                       80  ...   
wxb12345                       80          73                       80  ...   

          quiz 4  quiz 5  Exam 1 Score  Exam 2 Score  Exam 3 Score  \
SID                                                                  
axl60952       8       8          0.79          0.63          0.68   
amc28428       7      12          0.65          0.63          0.90   
axc64717      12      11          0.65          0.78          0.83   
akr14831      11       7          0.97          0.97          0.81   
axd11293       5       6          0.68          0.95          0.88   
...          ...     ...           ...           ...           ...   
txw75701       9       8          0.94          0.74          0.68   
tbr17292       7       5          0.91          0.67          1.00   
vkb66346       6       8          0.68          0.93          0.69   
wad63934       9       5          0.84          0.91          0.95   
wxb12345       7      10          0.86          0.62          0.90   

          Homework Score  Quiz Score  Final Score  Ceiling Score  Grade  
SID                                                                      
axl60952        0.912500    0.594203     0.723841           73.0      C  
amc28428        0.983333    0.710145     0.788196           79.0      C  
axc64717        0.879167    0.724

### NumPy Project

In [20]:
# create a 1D numpy array with 10 different elements and extract the elements from the third to sixth position
X = np.random.randint(0, 30, 10)
print("The 1D array: ", X)
print("The elements from the 3rd to 6th position in the array:", X[3:7])

The 1D array:  [ 1 27 14 15  1 25  8  5 27 10]
The elements from the 3rd to 6th position in the array: [15  1 25  8]


In [21]:
# Create a 3x3 NumPy array filled with zeros. What is the resulting array?
Y = np.zeros((3, 3), dtype=int)
print("The resulting array is:\n", Y)

The resulting array is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
# Given a NumPy array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract the element at the second row and third column.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1,2])

6


In [23]:
# Create a 3x3 identity matrix using NumPy and compute the dot product of two given matrices.
id = np.identity(3, dtype=int)
id

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
# Create a 3x3 identity matrix using NumPy. Compute the dot product of two given matrices.
print(np.dot(arr, id))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# Resize a 2D NumPy array to have 5 rows and pad with zeros if necessary.
example = np.random.randint(10, size=(2, 3))
print("2D array:\n", example)
example.resize(5,3)
print("Resized array:\n", example)

2D array:
 [[6 2 1]
 [5 8 9]]
Resized array:
 [[6 2 1]
 [5 8 9]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Congratulations Queens, I am sure this project has expanded your use of Pandas and NumPY in understanding and manipulating data